fix:  gh self-hosted runner workflow (#25)
* fix: use new pm api token

* fix: do not run on machine being managed

* add gh runner env tfvars

* fix: ssh to pve isssue

* fix: gh worker static count

* fix: persist ssh agent envs

* fix: broken indentation on pm private key

* fix: registration token not generated

* fix: registration token bad naming

diff --git a/.github/workflows/gh-runner-deploy.yaml b/.github/workflows/gh-runner-deploy.yaml
--- a/.github/workflows/gh-runner-deploy.yaml
+++ b/.github/workflows/gh-runner-deploy.yaml
@@ -5,15 +5,22 @@ permissions:
 on:
   workflow_dispatch:
     inputs:
-      resource_count:
-        description: 'Total number of self-hosted runners that should be deployed (if number is smaller than current, excess runners will be destroyed)'
+      is_controller:
+        description: 'Deploy controller (true) or worker (false)'
         required: true
-        default: ''
+        type: boolean
+        default: false
+      resource_count:
+        description: 'Number of worker runners (ignored if deploying controller)'
+        required: false
+        default: '1'
 
 env:
-  PROXMOX_VE_API_TOKEN: '${{ vars.PM_API_TOKEN_ID }}=${{ secrets.PM_API_TOKEN }}'
+  PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
   TF_VAR_admin_password: ${{ secrets.CI_EXAMPLE_ROOT_PASS }}
-  TF_VAR_instance_count: ${{ inputs.resource_count }}
+  TF_WORKSPACE: ${{ inputs.is_controller && 'GH-Controller' || 'GH-Worker' }}
+  TF_VAR_instance_count: ${{ inputs.is_controller && '1' || inputs.resource_count }}
+  TF_VAR_proxmox_private_key: ${{ secrets.PROXMOX_PRIVATE_KEY }}
 
 jobs:
   generate-token:
@@ -26,15 +33,18 @@ jobs:
       id: registration
       run: |
         TOKEN=$(curl -s -X POST \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
           -H "Accept: application/vnd.github+json" \
           https://api.github.com/repos/krakenhavoc/HomeLab/actions/runners/registration-token \
           | jq -r .token)
 
-        echo "REGISTRATION_TOKEN=$TOKEN" >> $GITHUB_OUTPUT
+        # Verify it's not empty before setting output
+        if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then echo "Token generation failed"; exit 1; fi
+
+        echo "token=$TOKEN" >> $GITHUB_OUTPUT
 
   deploy:
-    runs-on: self-hosted
+    runs-on: ${{ inputs.is_controller && 'worker' || 'controller' }}
     needs: generate-token
     env:
         NODE_OPTIONS: "--no-network-family-autoselection"
@@ -54,6 +64,13 @@ jobs:
       with:
         cli_config_credentials_token: ${{ secrets.HCP_API_TOKEN }}
 
+    - name: Set up SSH for Proxmox Provider
+      run: |
+        eval $(ssh-agent -s)
+        ssh-add ~/.ssh/id_proxmox
+        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
+        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
+
     - name: Terraform Init
       working-directory: terraform/deployments/gh-runner
       run: terraform init -input=false
@@ -64,4 +81,9 @@ jobs:
 
     - name: Terraform Apply
       working-directory: terraform/deployments/gh-runner
-      run: terraform apply -auto-approve
+      run: |
+        if [ "${{ inputs.is_controller }}" = "true" ]; then
+          terraform apply -auto-approve -var-file=env/gh-controller.tfvars
+        else
+          terraform apply -auto-approve -var-file=env/gh-worker.tfvars
+        fi
